---
title: "p8105_hw3_ys3765"
author: "Yixiao Sun"
date: "2023-10-09"
output: github_document
---
#Problem 1
```{r}
library(tidyverse)
library(p8105.datasets)
library(ggplot2)
data("instacart")
```


#Problem 2

```{r problem2 data cleaning}
library(p8105.datasets)
data("brfss_smart2010")

df1 = brfss_smart2010%>%
  janitor::clean_names()

dic_levels = c("Poor","Fair","Good","Very good","Excellent")

df1_grouped<-df1%>%
  group_by(topic = "Overall Health")%>%
  filter(response %in% dic_levels)

df1_grouped_ordered<-df1_grouped %>%
  mutate(response = factor(response,levels = c("Poor","Fair","Good","Very good","Excellent"), ordered=TRUE))
  
```

```{r problem 2 questions coding}
states_2002 <- df1_grouped_ordered %>%
  filter(year == 2002) %>%
  distinct(locationabbr,locationdesc)%>%
  count(locationabbr)%>%
  filter(n >= 7)

print(states_2002)

states_2010 <- df1_grouped_ordered %>%
  filter(year == 2010) %>%
  distinct(locationabbr,locationdesc)%>%
  count(locationabbr)%>%
  filter(n >= 7)

print(states_2010)
```
```{r construct}
excellent<-df1_grouped_ordered%>%
  filter(response == "Excellent")%>%
  group_by(year,locationabbr)%>%
  summarise(average = mean(data_value,.groups='drop'))

ggplot(excellent, aes(x = year, y = average, group = locationabbr, color = locationabbr)) +
  geom_line() +
  labs(title = "Average Value of 'Excellent' Responses Over Time", 
       x = "Year", 
       y = "Average Value") +
  theme_minimal() 
```

```{r two_panel plot}
ny_data <- df1_grouped_ordered %>%
  filter(year %in% c(2006, 2010), locationabbr == "NY")

# Make a two-panel plot
ggplot(ny_data, aes(x = response, y = data_value)) +
  geom_boxplot() +
  facet_grid(~year) +
  labs(title = "Distribution of Data Value in NY for 2006 and 2010", 
       x = "Response", 
       y = "Data Value")


```




#Problem 3
```{r read the csv and tidy and merge}
nhanes_accel <- read_csv("data/nhanes_accel.csv")%>%
  janitor::clean_names()%>%
  pivot_longer(min1:min1440,names_to = "table",values_to = "value")

nhanes_covar <- read_csv("data/nhanes_covar.csv", skip = 4) %>%
  janitor::clean_names()%>%
  mutate(sex = recode(sex,`1` = "Male", `2`= "Female"),
         education = recode(education,
                            `1` = "Less than high school", 
                            `2` = "High school equivalent", 
                            `3` = "More than High School" ))%>%
  na.omit()



view(nhanes_covar)
merge_data<-left_join(nhanes_covar,nhanes_accel,by = "seqn")

clean_data <- merge_data %>%
  filter(age >= 21) %>%
  mutate(education = factor(education, levels = c("Less than high school", 
                                                  "High school equivalent", 
                                                  "More than High School"), 
                            ordered = TRUE))

```


```{r create a table}
education_gender_table <- clean_data %>%
  group_by(education, sex) %>%
  summarize(n_obs = n())

print(education_gender_table)
```
```{r Visualization of the age distribution for men and women in each education categoru}
clean_data_plot = 
  clean_data %>%
  ggplot(aes(x = education, y = age, color =sex)) +
  geom_boxplot() +
  labs(title = "Age Distributions by Gender and Education", x = "Education", y = "Age")
clean_data_plot
```



```{r total activity plot}
total<- clean_data%>%
        group_by(clean_data$seqn)%>%
        mutate(total = sum(value))

ggplot(total,aes(x = age, y = total,color = sex))+
  geom_point()+
  geom_smooth()+
  facet_wrap(~education)+
  labs(title = "Total Activity vs Age by Education and Gender")
              
```

```{r}
ggplot(clean_data, aes(x = table, y = value,color = sex))+
  geom_point(alpha = 0.5)+
  geom_smooth()+
  facet_wrap(~education)+
  labs(title = "Activity time over 24-Hours by Education and Gender")
```

